# This file generates the GitHub Actions matrix.
include:
  # ZMK Studio 対応ビルド (通常はこれを使う)
  - board: seeeduino_xiao_ble
    shield: wobo40
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: wobo40-studio
  # Studio なしの軽量ビルド
  - board: seeeduino_xiao_ble
    shield: wobo40
    artifact-name: wobo40
  # ペアリング情報を消去するリセット用ファームウェア
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings-reset
